version: "2"

run:
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - sloglint

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - Close
  
  sloglint:
        no-mixed-args: true
        key-naming-case: "snake"
        attr-naming-case: "snake"
        context: "only"

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes: ynastt/avito_test_task_backend_2025

issues:
  exclude-use-default: false

  exclude:
    - "Error return value of `rows.Close` is not checked"

  fast: true
  severity: warning

output:
    format: colored-line-number
    print-issued-lines: true
    print-linter-name: true